name: Github Action to build pdf from tex source.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
          # the root LaTeX file to be compiled
          root_file: main.tex
          # extra arguments to be passed to the LaTeX engine
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          # install extra packages by apk
          # extra_system_packages: # optional
          # install extra .ttf/.otf fonts.
          # extra_fonts: ./fonts/*.ttf
          # arbitrary bash codes to be executed before compiling LaTeX documents
          # instruct latexmk to enable --shell-escape
          latexmk_shell_escape: true
          pre_compile: tlmgr update --self && tlmgr update --all
          # arbitrary bash codes to be executed after compiling LaTeX documents
          post_compile: latexmk -c
          # instruct latexmk to use XeLaTeX
          latexmk_use_xelatex: true 

    - name: Check pdf file
      run: |
        file main.pdf | grep -q ' PDF '

    - name: Upload file to repository
      run: |
        git config --global user.name "jr-leary7"
        git config --global user.email "jrleary@live.unc.edu"
        git add main.pdf
        git commit -m "compiled study guide"
        git push
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
